### ISSUE TITLE
looks for  psmgwparms

### ISSUE THREAD

**Issue by ewitkop** [strick-j/ca-html5gw#27]
[root@html5 ca-html5gw]# rpm -ivh CARKpsmp-12.06.0.26.x86_64.rpm 
warning: CARKpsmp-12.06.0.26.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 08beaa44: NOKEY
Preparing...                          ################################# [100%]
Installation process is starting...
Installation failed. Reason: installation parameters file [/var/tmp/psmpparms] doesn't exist.

**Comment by strick-j** [comment]
Is this error related to a different repo? PSMP is not installed as part of HTML5GW install.

**Comment by ewitkop** [comment]
I was wondering if I needed to install the RPM prior to running your script. At the beginning of the script, it would be cool if it would echo what prereq packages we need to install prior. And even check for their existence and then exit0 if they are missing.

**Comment by strick-j** [comment]
To install the HTML5GW you shouldn't need to install the RPM prior to running this script. The goal of this script is to basically automate the manual install documented here: [HTML5GW](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PAS%20INST/Install_PSM_HTML5_RPM.htm?tocpath=Installation%7CInstall%20PAM%20-%20Self-Hosted%7CInstall%20PSM%7CAdvanced%20PSM%20Implementations%7CInstall%20PSM%20HTML5%20Gateway%7C_____3) 

Ideally, nothing needs to be installed prior to running. The first stage of the script checks for required yum packages and installs them. In Step 5 the script searches for the RPM which you would obtain from CyberArk and installs it. I could move this check to the beginning and exit on missing RPM. Would that solve the overall issue?

**Comment by ewitkop** [comment]
Let's try it. Let's take a fresh CentOS7 and see if we can get it to run
flawlessly.

**Comment by strick-j** [comment]
I've made some updates that prompt the user to enable JWT based auth. Based on this I ran the install twice on unique centos ec2 instances; once with JWT enabled and once with JWT disabled. Both installations were successful. A successful run example is below: 
```

===========================================================================
Step 1: Installing system updates and required prerequisite packages
===========================================================================

INFO: Validating HTMl5GW rpm is present
SUCCESS: Installation rpm is present, proceeding...
SUCCESS: GPG Key is present, proceeding...
INFO: Verifying firewalld is installed
WARNING: firewalld is not installed. Adding to list of packages to install.
INFO: Installing New Packages - This may take some time
INFO: Installing firewalld
SUCCESS: firewalld installed.
INFO: Installing cairo
SUCCESS: cairo installed.
INFO: Installing libpng
SUCCESS: libpng installed.
INFO: Installing libjpeg-turbo
SUCCESS: libjpeg-turbo installed.
INFO: Installing wget
SUCCESS: wget installed.
INFO: Installing java-1.8.0-openjdk
SUCCESS: java-1.8.0-openjdk installed.
INFO: Installing java-1.8.0-openjdk-devel
SUCCESS: java-1.8.0-openjdk-devel installed.
INFO: Installing openssl
SUCCESS: openssl installed.
SUCCESS: Required packages installed.

===========================================================================
Step 2: Collecting user provided information
===========================================================================

INFO: Have you read and accepted the CyberArk EULA?
1) Yes
2) No
#? 1
INFO: EULA Accepted, proceeding...
INFO: Would you lke to enable JWT for additional security (Yes or No)?
1) Yes
2) No
#? 1
Please enter the hostname of the CyberArk PVWA: pvwa.example.com
INFO: You entered pvwa.example.com, is this correct (Yes or No)?
1) Yes
2) No
#? 1
INFO: Updating psmgwparms file with user provided information
INFO: psmgwparms file modified, proceeding...
Please enter fully qualified domain name or hostname: html5gw.example.com
INFO: You entered html5gw.example.com, is this correct (Yes or No)?
1) Yes
2) No
#? 1

===========================================================================
Step 3: Installing and configuring Apache Tomcat
===========================================================================

INFO: Setting up Apache Tomcat user
INFO: Searching for correct Apache URL
SUCCESS: URL Found: https://downloads.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz
INFO: Downloading Apache Tomcat v9.0.73
INFO: Apache Tomcat v9.0.73 download succesful - Installing Now
INFO: Setting Tomcat folder permissions
INFO: Creating Tomcat Service
INFO: Creating Tomcat Self Signed Certificate
INFO: Checking /opt/secrets/keystore keystore for psmgw alias
SUCCESS: psmgw successfully imported into /opt/secrets/keystore keystore
INFO: Exporting Tomcat Certificate from Keystore
SUCCESS: Apache Tomcat installed and configured

===========================================================================
Step 4: Configuring firewall
===========================================================================

INFO: Verifying firewalld is installed
SUCCESS: firewalld is installed
INFO: Checking status of firewalld
WARNING: firewalld is not running, would you like to start it?
1) Yes
2) No
#? 1

SUCCESS: firewalld started
INFO: Configuring Firewall for PSMGW
INFO: Gathering active firewall zone information
INFO: Active zone is success, gathering forward port information
INFO: Verifying forward ports are correct
SUCCESS: Port 443 Port Forwarding is correct
SUCCESS: Port 80 Port Forwarding is correct
SUCCESS: Firewall configured

===========================================================================
Step 5: Installing and configuring HTML5 PSMGW
===========================================================================

INFO: Verifying rpm GPG Key is present
INFO: GPG Key present - Importing...
INFO: GPG Key imported, proceeding...
INFO: Verifying PSMGW has been placed within the repository
INFO: PSMGW file found, installing now
SUCCESS: PSMGW Installed
INFO: Updating Guacamole Configuration File
SUCCESS: Completed guacamole configure file modifications
INFO: Updating guacamole SSL configuration file
SUCCESS: Completed guacamole SSL configure file modifications
INFO: Generating self signed certificates for Guacamole
INFO: Checking /opt/secrets/keystore keystore for psmgw_guacd_cert alias
SUCCESS: psmgw_guacd_cert successfully imported into /opt/secrets/keystore keystore
SUCCESS: Guacamole certificates imported into Apache Keystore
INFO: Checking /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-1.el7_9.x86_64/jre//lib/security/cacerts keystore for psmgw_guacd_cert alias
SUCCESS: psmgw_guacd_cert successfully imported into /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-1.el7_9.x86_64/jre//lib/security/cacerts keystore
SUCCESS: Guacamole certificates imported into Java Keystore
INFO: Restarting Tomcat and Guacamole
INFO: Checking on status of Tomcat Service
SUCCESS: tomcat is running!
INFO: Checking on status of Guacamole Service
SUCCESS: guacd is running!
```

**Comment by ewitkop** [comment]
That looks amazing!! I can't wait to take her for a test run.

**Comment by strick-j** [comment]
Note: if you dont put the GPG Key and RPM file in the folder you are running the script from the install will stop at the beginning and let you know they are missing.

Does this solve your issue? Also, the latest method of installing the HTML5GW that most people use is via a container. Have you looked at using that method? [Container Install](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PAS%20INST/Install_PSM_HTML5_Docker.htm?TocPath=Installation%7CInstall%20PAM%20-%20Self-Hosted%7CInstall%20PSM%7CAdvanced%20PSM%20Implementations%7CInstall%20PSM%20HTML5%20Gateway%7C_____1)

**Comment by ewitkop** [comment]
I have a container system built now.  The only weird part for me was
specifying the cert folder. I used SSC's, and I was a bit confused as to
why I need to point to a folder or where the folder is, exactly. Is it in
the host? Is it inside the container itself.
I think that part of it is confusing.  I ended up grabbing the default of
/opt/cert but I was not 100% sure as I did it.
